#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir
cp -r 0.orig/ 0/


runApplication blockMesh

runApplication topoSet

runApplication createPatch -overwrite

runApplication decomposePar -force

runParallel $(getApplication)

runApplication reconstructPar
#------------------------------------------------------------------------------
